-- Extend the user role enum to match the current Prisma schema and demo seed.
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'MANAGER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'WAITER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'CASHIER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'KITCHEN';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'BAR';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'INVENTORY';
