
####
GET localhost:5000/api/v1/pos/products

###
Get localhost:5000/api/health



### login
POST http://localhost:5000/api/auth/login
Content-Type: application/json  

{
  "email": "admin@safina.com",
  "password": "Admin@123"
}

#### get all products
GET  http://localhost:5000/api/menu
Content-Type: application/json


#### order list
GET  http://localhost:5000/api/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUxM2VmOTMxLTQ0OWEtNDVkNi1hZGI1LTkwYTUzZjQ5MjFlMSIsImVtYWlsIjoiYWRtaW5Ac2FmaW5hLmNvbSIsInJvbGUiOiJBRE1JTiIsIm5hbWUiOiJBZG1pbmlzdHJhdG9yIiwib3JnYW5pemF0aW9uSWQiOiJiNmFmNDI3OS1lZWJjLTQ0ZTktYTU4My00ZmY5ZmNkZGRjZjAiLCJpYXQiOjE3OTAzNjkwOTksImV4cCI6MTc5MDM2OTk5OX0.m36yg3aqRd84W0wW6P1Y31Pcg2wyMRQbLEfXzLZ5HpA